{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.1/koruksp-0.12.1.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-watchosarm32-0.12.1.klib",
          "size": 12761,
          "sha512": "37afe89a1dbb77aa54d90cf89ebba0b750f008d0eda6d84812697f2caebe65dbd44229491cf7b28bd48ab5323ccc3b587ce437b66283f84d0be9b57f46c93b89",
          "sha256": "f335e00c7426319d888f8ba652426a919011f71f6e4cde1914d2b561a5244526",
          "sha1": "b0de986475cebe351614675bf41cf61cd46e6904",
          "md5": "780b4a1c344b915c7e75788fab7ed841"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-watchosarm32-0.12.1-metadata.jar",
          "url": "koruksp-watchosarm32-0.12.1-metadata.jar",
          "size": 4066,
          "sha512": "4fafd5484285da0b0377c51aa920d842ba53e5e4d22430d5bfb38552b348ab53541e3505972578f23cd65983fca87914900bfe845b450448e1aef3031e995017",
          "sha256": "96301004908c430ba48593a699fd70538a5f0efdbf3cc02ef09b9e5e2e463145",
          "sha1": "efc02918be9971c21f72fcbbdbab750c4f1cf62e",
          "md5": "29ab14db894703ebd2454c80af6ec56f"
        }
      ]
    }
  ]
}
