{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.0/koruksp-0.12.0.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-watchossimulatorarm64-0.12.0.klib",
          "size": 12847,
          "sha512": "77d179531b2731a7388db5ea982bc4ff20faca79a35af9dc547b5a9fce77900fb864ee40bdde639a16f44e2711076443e88ffb21c0f832e2d562bcc65854158c",
          "sha256": "78d5d7fd7872ef49ee8c370f82d411ffd0ada2fc86acf33f1bb9dab19fc976b9",
          "sha1": "454081ada6da754d787c5117883e676f4be19a0c",
          "md5": "c71253455bf8bb21952e1ed978f269fd"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-watchossimulatorarm64-0.12.0-metadata.jar",
          "url": "koruksp-watchossimulatorarm64-0.12.0-metadata.jar",
          "size": 4066,
          "sha512": "7930bf2befa75b08eb08dec1388a9046451a8cd9dcb025039b43c08c4f9b8af4ea6531f25c11433d146af5ffb1c9f5a0f3183a5276cad62f8b26d4dd9e07f23c",
          "sha256": "206aa62178c76d7b4c7b573762a307cbf7724dbe8608ad36513d802c3c919daa",
          "sha1": "aca00de037ec777b5a7a45cd35c9ab8573e11771",
          "md5": "1a00bb6f393ff068b20c37c61f23310c"
        }
      ]
    }
  ]
}
