{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.0/koruksp-0.12.0.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-watchossimulatorarm64-0.12.0.klib",
          "size": 12847,
          "sha512": "77d179531b2731a7388db5ea982bc4ff20faca79a35af9dc547b5a9fce77900fb864ee40bdde639a16f44e2711076443e88ffb21c0f832e2d562bcc65854158c",
          "sha256": "78d5d7fd7872ef49ee8c370f82d411ffd0ada2fc86acf33f1bb9dab19fc976b9",
          "sha1": "454081ada6da754d787c5117883e676f4be19a0c",
          "md5": "c71253455bf8bb21952e1ed978f269fd"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-watchossimulatorarm64-0.12.0-metadata.jar",
          "url": "koruksp-watchossimulatorarm64-0.12.0-metadata.jar",
          "size": 4066,
          "sha512": "fe567dd021d217466826c78ed09438d0f129f3553d6388aa604a24f5a704fecd999409bfa3f41de89e476e8b231d8f45ff522d8e896a67f2e70653db6b1b1027",
          "sha256": "e66a347e6ae094a244bec514d24905d1c948a41e8190b8c93072fd60ee58b963",
          "sha1": "0c902210876029227bfce7987661d8db5fd6ac66",
          "md5": "674f25d76b0df4c5c4a69e32211ed1cc"
        }
      ]
    }
  ]
}
