{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.0/koruksp-0.12.0.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-tvosarm64-0.12.0.klib",
          "size": 12734,
          "sha512": "979410b5dffeb7fc6beb04865208dc857a177f08345909ab05b876581bd0940a66296923e793046c39e4d669e4cfeb57380a4b31a2f057ad616695932521d474",
          "sha256": "d60e077a19f7baea63bf37c914c624a44c39a21ca9002fb874280706abc9f818",
          "sha1": "2b07c8e7632a0403d58ebd0e0de96a17fa43d634",
          "md5": "fd17f794fa53573c05a72703fbb8173e"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-tvosarm64-0.12.0-metadata.jar",
          "url": "koruksp-tvosarm64-0.12.0-metadata.jar",
          "size": 4066,
          "sha512": "fe567dd021d217466826c78ed09438d0f129f3553d6388aa604a24f5a704fecd999409bfa3f41de89e476e8b231d8f45ff522d8e896a67f2e70653db6b1b1027",
          "sha256": "e66a347e6ae094a244bec514d24905d1c948a41e8190b8c93072fd60ee58b963",
          "sha1": "0c902210876029227bfce7987661d8db5fd6ac66",
          "md5": "674f25d76b0df4c5c4a69e32211ed1cc"
        }
      ]
    }
  ]
}
