{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.11.0/koruksp-0.11.0.module",
    "group": "com.futuremind.koruksp",
    "module": "koruksp",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-tvosarm64-0.11.0.klib",
          "size": 12718,
          "sha512": "6fd9474437cef3a209c0e10122099d4be29dfb4ae351f201d1911852ff1f55a99fc9d44fb553c409cc95fe136d9c1131cb809199ef02fc9665c9c270e7e6c8b0",
          "sha256": "a2a9ba495253987dfd2f6ad8688f248b50b3450cc8c8e900e1b85317c37cf84a",
          "sha1": "3f2e8fa13b0396046bf1edf22740dcce57cd5cb9",
          "md5": "559ef66bb68365b5e2ba8b1202577469"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-tvosarm64-0.11.0-metadata.jar",
          "url": "koruksp-tvosarm64-0.11.0-metadata.jar",
          "size": 4051,
          "sha512": "3b31f89f76157014d83c859f5eff018c540faa21ce2e2bf735b31b8d038ff36380395c62d4a477eb9fa29750ad1ba55235e5d354bc7e8046325794aa2dd90630",
          "sha256": "0a0dcb65189fc4d20dd0d0a69f3c218e9d1345d41ddc2242dda7b866dc0eda32",
          "sha1": "345fc6991536d2e130232e8681296ac1dc9b6ce7",
          "md5": "7ee3d93479ef416cf9a620190dbdd965"
        }
      ]
    }
  ]
}
