{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.11.0/koruksp-0.11.0.module",
    "group": "com.futuremind.koruksp",
    "module": "koruksp",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-watchosarm64-0.11.0.klib",
          "size": 12744,
          "sha512": "f0f76684382fcc51e36c77db0b36133121f8a061445dc8fc5d3bf385c61c3b4bb57b51a8239ac837fb3aabec9548aa90ffdd2693091bbf6387b382e10f254566",
          "sha256": "7e4920fbb09feb944bc7d93e468110d13363ac8f4b694fb4c449eb12f740a79e",
          "sha1": "8f42b8e80920a20d6423eb24135093597e484ebc",
          "md5": "a3f167e918328a6ef0aa3f0da3d6192d"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-watchosarm64-0.11.0-metadata.jar",
          "url": "koruksp-watchosarm64-0.11.0-metadata.jar",
          "size": 4051,
          "sha512": "3b31f89f76157014d83c859f5eff018c540faa21ce2e2bf735b31b8d038ff36380395c62d4a477eb9fa29750ad1ba55235e5d354bc7e8046325794aa2dd90630",
          "sha256": "0a0dcb65189fc4d20dd0d0a69f3c218e9d1345d41ddc2242dda7b866dc0eda32",
          "sha1": "345fc6991536d2e130232e8681296ac1dc9b6ce7",
          "md5": "7ee3d93479ef416cf9a620190dbdd965"
        }
      ]
    }
  ]
}
