{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.0/koruksp-0.12.0.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-jvm-0.12.0.jar",
          "url": "koruksp-jvm-0.12.0.jar",
          "size": 15330,
          "sha512": "87266ab253e2c6adb5fd5b4f5095092bb75c2a16690c33ffa7dbbaa23481bbaba47a31ae2741983f9e1d9c118107a1fb9b457ba099cd04d08cb5f94d938b8374",
          "sha256": "d682e3072ade8fb36236f8b2ca9b9f24bcb5a450207a3a2c3980c47504bdeb92",
          "sha1": "8b56a9d9934130af3a9b060bd6dffac13c8c0aa7",
          "md5": "fda20aee7efe364948d8aa96a7c38a40"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-jvm-0.12.0.jar",
          "url": "koruksp-jvm-0.12.0.jar",
          "size": 15330,
          "sha512": "87266ab253e2c6adb5fd5b4f5095092bb75c2a16690c33ffa7dbbaa23481bbaba47a31ae2741983f9e1d9c118107a1fb9b457ba099cd04d08cb5f94d938b8374",
          "sha256": "d682e3072ade8fb36236f8b2ca9b9f24bcb5a450207a3a2c3980c47504bdeb92",
          "sha1": "8b56a9d9934130af3a9b060bd6dffac13c8c0aa7",
          "md5": "fda20aee7efe364948d8aa96a7c38a40"
        }
      ]
    }
  ]
}
