{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.0/koruksp-0.12.0.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-jvm-0.12.0.jar",
          "url": "koruksp-jvm-0.12.0.jar",
          "size": 15330,
          "sha512": "17954e632dbdd8535101608a510eaa9fd84d699f4122e0d7101d42509c7b0a031485ef3d0680f2d80b0a6067437300abf8029fdd38545612de8b7e9a14201f40",
          "sha256": "331d2a6c2fa4b886b04cd592d52dee0661336cd7caf2bdc9bf09206af79bb3b2",
          "sha1": "b4e9721e0a0263adc542574b210c7c04b205183a",
          "md5": "a737208213021bc707306c622c2a9880"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-jvm-0.12.0.jar",
          "url": "koruksp-jvm-0.12.0.jar",
          "size": 15330,
          "sha512": "17954e632dbdd8535101608a510eaa9fd84d699f4122e0d7101d42509c7b0a031485ef3d0680f2d80b0a6067437300abf8029fdd38545612de8b7e9a14201f40",
          "sha256": "331d2a6c2fa4b886b04cd592d52dee0661336cd7caf2bdc9bf09206af79bb3b2",
          "sha1": "b4e9721e0a0263adc542574b210c7c04b205183a",
          "md5": "a737208213021bc707306c622c2a9880"
        }
      ]
    }
  ]
}
