{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp-processor/0.11.0/koruksp-processor-0.11.0.module",
    "group": "com.futuremind.koruksp",
    "module": "koruksp-processor",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-processor-jvm-0.11.0.jar",
          "url": "koruksp-processor-jvm-0.11.0.jar",
          "size": 28094,
          "sha512": "eca0f900911900b85d010350c0623c56925121796070191766929a9b310c10b374d5b450a7e3e46f2e3d340545add49ec482282611627eda2f4c17b58046ce04",
          "sha256": "3729a95f02c1dadc06f653be08949a5c0a0e7950b3068549f90cb765773e741d",
          "sha1": "40dbd7ed70ade4511a0530dddb81dcfaaa8ffade",
          "md5": "c5cc14de35410caa599d30d39690a2bc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.futuremind.koruksp",
          "module": "koruksp",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-processor-jvm-0.11.0.jar",
          "url": "koruksp-processor-jvm-0.11.0.jar",
          "size": 28094,
          "sha512": "eca0f900911900b85d010350c0623c56925121796070191766929a9b310c10b374d5b450a7e3e46f2e3d340545add49ec482282611627eda2f4c17b58046ce04",
          "sha256": "3729a95f02c1dadc06f653be08949a5c0a0e7950b3068549f90cb765773e741d",
          "sha1": "40dbd7ed70ade4511a0530dddb81dcfaaa8ffade",
          "md5": "c5cc14de35410caa599d30d39690a2bc"
        }
      ]
    }
  ]
}
