{
  "formatVersion": "1.1",
  "component": {
    "group": "com.futuremind.koruksp",
    "module": "koruksp-processor",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-processor-metadata-0.11.0-all.jar",
          "url": "koruksp-processor-0.11.0-all.jar",
          "size": 676,
          "sha512": "3d2e8c97c9a3ac81ff643a34e1a0d1f8662999e0d3ce92a01e01adca51ce0086272e599cc316455843b54d8497e0b49c66fc1b7531ed0471db2f27082c79a94b",
          "sha256": "49f7b5e0b2897921c542e46ee4b0e3c9a8d92e90e9b0252b76c762b6cce332a7",
          "sha1": "a2ff2e24b117d0f9e76628fb814cae4a6143e834",
          "md5": "556d7bbbf13543d09cfa320899af308a"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-processor-0.11.0.jar",
          "url": "koruksp-processor-0.11.0.jar",
          "size": 261,
          "sha512": "3dbf48b960c06007bf1d0840c7fcd8212134b9674eecde6cd193c4f9f27826f2cde3b260320a3c0aaaed6e887517266aca99a1042737cc6f244e5fbae1e1eb99",
          "sha256": "166da91d2dc9b1b527424af4a4bb01e5ae2458fd107e625aceb5ab5f1961f0b7",
          "sha1": "2990ba6dca646ef0f6ce8be8517a6b31c128d621",
          "md5": "c293af6a5cc2737d683e44df38f67ccb"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koruksp-processor-jvm/0.11.0/koruksp-processor-jvm-0.11.0.module",
        "group": "com.futuremind.koruksp",
        "module": "koruksp-processor-jvm",
        "version": "0.11.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koruksp-processor-jvm/0.11.0/koruksp-processor-jvm-0.11.0.module",
        "group": "com.futuremind.koruksp",
        "module": "koruksp-processor-jvm",
        "version": "0.11.0"
      }
    }
  ]
}
