{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.0/koruksp-0.12.0.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-tvosx64-0.12.0.klib",
          "size": 12717,
          "sha512": "710e0d6239019c3ccbb7a0b79f630b4ef7de5b694a927125a80d2ac162c84e7b4fc6a9c059f3b191abafd81a82053c42299c1d8a000554b1ca0320103f4f8f2e",
          "sha256": "7b8e2b74512d7ac77b77a0eadb140a2b656e28f6931d9905421e3f6b2fa0fac0",
          "sha1": "f2c63ae2a95440b81d09d5a1006fc35c4d98ba4f",
          "md5": "d4394694756fa023144a9687a1e81e08"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-tvosx64-0.12.0-metadata.jar",
          "url": "koruksp-tvosx64-0.12.0-metadata.jar",
          "size": 4066,
          "sha512": "7930bf2befa75b08eb08dec1388a9046451a8cd9dcb025039b43c08c4f9b8af4ea6531f25c11433d146af5ffb1c9f5a0f3183a5276cad62f8b26d4dd9e07f23c",
          "sha256": "206aa62178c76d7b4c7b573762a307cbf7724dbe8608ad36513d802c3c919daa",
          "sha1": "aca00de037ec777b5a7a45cd35c9ab8573e11771",
          "md5": "1a00bb6f393ff068b20c37c61f23310c"
        }
      ]
    }
  ]
}
