{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.0/koruksp-0.12.0.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-tvosx64-0.12.0.klib",
          "size": 12717,
          "sha512": "710e0d6239019c3ccbb7a0b79f630b4ef7de5b694a927125a80d2ac162c84e7b4fc6a9c059f3b191abafd81a82053c42299c1d8a000554b1ca0320103f4f8f2e",
          "sha256": "7b8e2b74512d7ac77b77a0eadb140a2b656e28f6931d9905421e3f6b2fa0fac0",
          "sha1": "f2c63ae2a95440b81d09d5a1006fc35c4d98ba4f",
          "md5": "d4394694756fa023144a9687a1e81e08"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-tvosx64-0.12.0-metadata.jar",
          "url": "koruksp-tvosx64-0.12.0-metadata.jar",
          "size": 4066,
          "sha512": "fe567dd021d217466826c78ed09438d0f129f3553d6388aa604a24f5a704fecd999409bfa3f41de89e476e8b231d8f45ff522d8e896a67f2e70653db6b1b1027",
          "sha256": "e66a347e6ae094a244bec514d24905d1c948a41e8190b8c93072fd60ee58b963",
          "sha1": "0c902210876029227bfce7987661d8db5fd6ac66",
          "md5": "674f25d76b0df4c5c4a69e32211ed1cc"
        }
      ]
    }
  ]
}
