{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.11.0/koruksp-0.11.0.module",
    "group": "com.futuremind.koruksp",
    "module": "koruksp",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-iosarm64-0.11.0.klib",
          "size": 12709,
          "sha512": "c37626518043d4045a17f9f2737afc3ddfd458591ba66c0512e86b12a1bc0078acc8c4cef3ea28e395b9d787e2e370b58cc2727bd9261c89c82a5fdefa8f740f",
          "sha256": "b0762b382db6c662c3f556dcfeb238f0a6973cb08ab60f25f171a71df0df531b",
          "sha1": "90d1470d065a74672b8568e3194178633a661fc0",
          "md5": "9ef06aac11bf75f156034723d17d7285"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-iosarm64-0.11.0-metadata.jar",
          "url": "koruksp-iosarm64-0.11.0-metadata.jar",
          "size": 4051,
          "sha512": "7c9a1813c618941b85e1ace8630e00fdf23a03586ebb456c0636928860ddbb5acf7ba567102114605bae414a12509625ded018d2723355c6724b6f861fef5f3f",
          "sha256": "004c8ffdd563ec7bc3072f8c7ebf305096cadbbbd4dbe9c2a61811053bba1bf2",
          "sha1": "db680355c2ca8ee3cb9a18d18984c2411860192e",
          "md5": "3d67e07779d0c518c13d614669a5add7"
        }
      ]
    }
  ]
}
