{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-metadata-0.12.0-all.jar",
          "url": "koruksp-0.12.0-all.jar",
          "size": 4521,
          "sha512": "c220689a45f5a0c9bdb90ea7bcbcb75e7d3efd11f1fb279f87ef4f38468c5583bdbd095337f7a7437c6652b2b6b2244c5f88110b61a1a80a2ebb4aa7b9f43ed3",
          "sha256": "741171293bf6c49ccbe29891b5dca9250876307e50ecadfa577db083602d877b",
          "sha1": "293e25e55cad0c4803558426bb04662a8570650e",
          "md5": "1803c461b63b4bdad71c8ec0fb5b9c9d"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-0.12.0.jar",
          "url": "koruksp-0.12.0.jar",
          "size": 3932,
          "sha512": "e208fdd0f0fd81b68ea0b817b10918aedd6f3284ae339fabe7df6e9433f84292a3c9707e08349f84010cbcfe6c5785b9443743aa88a9cc20edac896f78af5c66",
          "sha256": "27fb44bc70f941d59da2fef287364016558997660d6ca8d95fbfc0dca48cd10c",
          "sha1": "576e1a8667f7b5454c83237f1d71670ad2cea608",
          "md5": "27d19e555a92981d9368a43da20c418d"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-iosarm64/0.12.0/koruksp-iosarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-iosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-iosarm64/0.12.0/koruksp-iosarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-iosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-iossimulatorarm64/0.12.0/koruksp-iossimulatorarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-iossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-iossimulatorarm64/0.12.0/koruksp-iossimulatorarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-iossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-iosx64/0.12.0/koruksp-iosx64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-iosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-iosx64/0.12.0/koruksp-iosx64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-iosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koruksp-jvm/0.12.0/koruksp-jvm-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-jvm",
        "version": "0.12.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koruksp-jvm/0.12.0/koruksp-jvm-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-jvm",
        "version": "0.12.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-macosarm64/0.12.0/koruksp-macosarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-macosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-macosarm64/0.12.0/koruksp-macosarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-macosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-macosx64/0.12.0/koruksp-macosx64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-macosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-macosx64/0.12.0/koruksp-macosx64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-macosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-tvosarm64/0.12.0/koruksp-tvosarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-tvosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-tvosarm64/0.12.0/koruksp-tvosarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-tvosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-tvossimulatorarm64/0.12.0/koruksp-tvossimulatorarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-tvossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-tvossimulatorarm64/0.12.0/koruksp-tvossimulatorarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-tvossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-tvosx64/0.12.0/koruksp-tvosx64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-tvosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-tvosx64/0.12.0/koruksp-tvosx64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-tvosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-watchosarm32/0.12.0/koruksp-watchosarm32-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-watchosarm32",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-watchosarm32/0.12.0/koruksp-watchosarm32-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-watchosarm32",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-watchosarm64/0.12.0/koruksp-watchosarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-watchosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-watchosarm64/0.12.0/koruksp-watchosarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-watchosarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-watchossimulatorarm64/0.12.0/koruksp-watchossimulatorarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-watchossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-watchossimulatorarm64/0.12.0/koruksp-watchossimulatorarm64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-watchossimulatorarm64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-watchosx64/0.12.0/koruksp-watchosx64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-watchosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-watchosx64/0.12.0/koruksp-watchosx64-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-watchosx64",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-watchosx86/0.12.0/koruksp-watchosx86-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-watchosx86",
        "version": "0.12.0"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koruksp-watchosx86/0.12.0/koruksp-watchosx86-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-watchosx86",
        "version": "0.12.0"
      }
    }
  ]
}
