{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp-processor/0.12.0/koruksp-processor-0.12.0.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp-processor",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-processor-jvm-0.12.0.jar",
          "url": "koruksp-processor-jvm-0.12.0.jar",
          "size": 28094,
          "sha512": "f8548dedaaf6fc1ae6e6769b52513512d5759a99add66a3dd062f22657557b5623312eb492071f4623bc18d2b3cb8addc618fdb8af7559047a440d3b60a98504",
          "sha256": "ee764ac247d8a3a1c72f333318ce10f7d231bb94bf47ccfbabb5df6310d3212b",
          "sha1": "abd5ac857a1c169283f7c138a810c4872d48b39e",
          "md5": "5ba81cc28e8261d415c48e372c98dba3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.github.hqzxzwb",
          "module": "koruksp",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-processor-jvm-0.12.0.jar",
          "url": "koruksp-processor-jvm-0.12.0.jar",
          "size": 28094,
          "sha512": "f8548dedaaf6fc1ae6e6769b52513512d5759a99add66a3dd062f22657557b5623312eb492071f4623bc18d2b3cb8addc618fdb8af7559047a440d3b60a98504",
          "sha256": "ee764ac247d8a3a1c72f333318ce10f7d231bb94bf47ccfbabb5df6310d3212b",
          "sha1": "abd5ac857a1c169283f7c138a810c4872d48b39e",
          "md5": "5ba81cc28e8261d415c48e372c98dba3"
        }
      ]
    }
  ]
}
