{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp-processor/0.12.0/koruksp-processor-0.12.0.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp-processor",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-processor-jvm-0.12.0.jar",
          "url": "koruksp-processor-jvm-0.12.0.jar",
          "size": 28227,
          "sha512": "d7f18a9e9bd3f517d77cccfed69154dfd85eefd95ada1a786f2b83462592554c705a7abe2addad60b218a831c4161f922c3cfa3262ba62e03239c04e54f7f6b7",
          "sha256": "13a025cb98a0a3ff567d17a1d90bab91169b34da95f79114a03394752292796b",
          "sha1": "bed83265c8444eef1bd9c71a80c9afd1bd78dfa6",
          "md5": "76395bfa83f5cd4c44f75f84c78d0c79"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.github.hqzxzwb",
          "module": "koruksp",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-processor-jvm-0.12.0.jar",
          "url": "koruksp-processor-jvm-0.12.0.jar",
          "size": 28227,
          "sha512": "d7f18a9e9bd3f517d77cccfed69154dfd85eefd95ada1a786f2b83462592554c705a7abe2addad60b218a831c4161f922c3cfa3262ba62e03239c04e54f7f6b7",
          "sha256": "13a025cb98a0a3ff567d17a1d90bab91169b34da95f79114a03394752292796b",
          "sha1": "bed83265c8444eef1bd9c71a80c9afd1bd78dfa6",
          "md5": "76395bfa83f5cd4c44f75f84c78d0c79"
        }
      ]
    }
  ]
}
