{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.1/koruksp-0.12.1.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-iosarm64-0.12.1.klib",
          "size": 12725,
          "sha512": "11b2010c103818cd68460ee30db1ffc1839337a97bec1317dee88c53c9c17b18582e7774fde9aa4f86a37ee7a09dd24345a30dd8a5ff13922e94c0de0419131d",
          "sha256": "92aad9060de490ed3990be181360d2ee471e604ec54dafd1f6c2d16297b7b70a",
          "sha1": "fdc0d5340e1a84a8ad7d5ec225ffa699c6f23cd5",
          "md5": "deb525215b24e7d3e1b1263e6757c394"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-iosarm64-0.12.1-metadata.jar",
          "url": "koruksp-iosarm64-0.12.1-metadata.jar",
          "size": 4066,
          "sha512": "f5c462ef141559443b017b39ab239b295c184c8a960cbe81ffe1030cf801f4aec4840e2562684096ad6b560925affaab16e426d806fca2c35b7a4eafda4d5d19",
          "sha256": "f26bfca55796ec6aaa04d81757e921c9ec2eaec957e5c528a122852d8a0fb7cf",
          "sha1": "9405e7246088abd41a503f9664cb17882b8210e6",
          "md5": "7896972c0faf322918fb78d2f8f383c4"
        }
      ]
    }
  ]
}
