{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.11.0/koruksp-0.11.0.module",
    "group": "com.futuremind.koruksp",
    "module": "koruksp",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-jvm-0.11.0.jar",
          "url": "koruksp-jvm-0.11.0.jar",
          "size": 15330,
          "sha512": "611b7b60b2ab595e96c3f5e48d006f2dd37b5dd2ee691c44cc02b419e6b0d5caa599eedcacc5ffb2137f777da0256836c4a949634d5199fedd4901c03d548ecc",
          "sha256": "3a32768a8200ae45879e21a9b78366eae4cbc69490eb77e5acd78455d2cba0a9",
          "sha1": "bcf4ea07cb698a15642c7333ac7f1deb6f77648b",
          "md5": "3992a1bbf3759a47e974a22ab5751d28"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-jvm-0.11.0.jar",
          "url": "koruksp-jvm-0.11.0.jar",
          "size": 15330,
          "sha512": "611b7b60b2ab595e96c3f5e48d006f2dd37b5dd2ee691c44cc02b419e6b0d5caa599eedcacc5ffb2137f777da0256836c4a949634d5199fedd4901c03d548ecc",
          "sha256": "3a32768a8200ae45879e21a9b78366eae4cbc69490eb77e5acd78455d2cba0a9",
          "sha1": "bcf4ea07cb698a15642c7333ac7f1deb6f77648b",
          "md5": "3992a1bbf3759a47e974a22ab5751d28"
        }
      ]
    }
  ]
}
