{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.0/koruksp-0.12.0.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-iosx64-0.12.0.klib",
          "size": 12708,
          "sha512": "eb638424116a0502b86093011d9518b71c347bc4a7adc547074c07103b30ad928ed414e845ab02c4337ab37de494eacdbc22f81ea819036b71844545838b31a8",
          "sha256": "8fde8991171a5a2ec6843add98c45cff4d67be85bc2394b8dc3a28d6b948909a",
          "sha1": "3361ec2b865f8bb82c88a6bc1048f0e2dddafaa4",
          "md5": "2983aa4fd51126ef546ddce21b15b27e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-iosx64-0.12.0-metadata.jar",
          "url": "koruksp-iosx64-0.12.0-metadata.jar",
          "size": 4066,
          "sha512": "aec5b1afab908c61f62c71fabc0eb84ba4ab5ce5ea1d9b9dba28973275faf758712783cf5483e8c5de00e5941a79905ff1c6ce501aa8ceed18960aa63fb5bc0a",
          "sha256": "91a3c457189a77b4c732dde00fe02625a183d30ed83d344caa4b9cc24d159eaa",
          "sha1": "6ccf2a114f2d1311d6dc07a8b7af490ef657b324",
          "md5": "1b811d90287b2297c1b7b76f64619ca5"
        }
      ]
    }
  ]
}
