{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hqzxzwb",
    "module": "koruksp-processor",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-processor-metadata-0.12.0-all.jar",
          "url": "koruksp-processor-0.12.0-all.jar",
          "size": 676,
          "sha512": "3f4bb993556274bcf3bec217f2e4e73e1a98e370ef8a3bc562374c4305972a92f6288f6bbcc3c588b93c19807274650896fee975537828ae52631305217dd0ca",
          "sha256": "adf50d8420ba818dc1ed4801291bc020c0cb8af34f140cf1b92266f8d0c52964",
          "sha1": "bc42bb4caf6a9852caadfa21f16dc3a56e37be2d",
          "md5": "d95e1a8aa47ab901a16acca030301978"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-processor-0.12.0.jar",
          "url": "koruksp-processor-0.12.0.jar",
          "size": 261,
          "sha512": "1f473974a92cdedc89354fb59e191b24307e4ac94b3dcd87915de359ada72fdd31dd8fb63db96cfac018f1bce682dc46dbd45d3ce4e7d40318e5fd742832ed80",
          "sha256": "7f710de29e5fb984ddaa3590d75699259d39ba373cd7171fe107dd1b28dcd8a8",
          "sha1": "857b412ad8465345c74f3952e73b3b775ee35dcf",
          "md5": "d45e9050551d8cbe94ffee7979c07bc6"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koruksp-processor-jvm/0.12.0/koruksp-processor-jvm-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-processor-jvm",
        "version": "0.12.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koruksp-processor-jvm/0.12.0/koruksp-processor-jvm-0.12.0.module",
        "group": "com.github.hqzxzwb",
        "module": "koruksp-processor-jvm",
        "version": "0.12.0"
      }
    }
  ]
}
