{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.12.1/koruksp-0.12.1.module",
    "group": "com.github.hqzxzwb",
    "module": "koruksp",
    "version": "0.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-watchosx64-0.12.1.klib",
          "size": 12743,
          "sha512": "3a1dbe9472d3f86930c36908e823eed9772a442bd86a34da93271bd6d6b01f19490a8f17af2d357d177ed7a08e08abd413a3aabfc7864f580a09710948ba061e",
          "sha256": "4e4352bb40dc5eab9bf3fd14c63e23b12751ef47bcf1b830dfbe1cee308ba0e2",
          "sha1": "d3bd179d2ca8bd9c625ddfcd976fc35c1316670b",
          "md5": "12f96a68abfcf51edd492d7366825fc6"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-watchosx64-0.12.1-metadata.jar",
          "url": "koruksp-watchosx64-0.12.1-metadata.jar",
          "size": 4066,
          "sha512": "4fafd5484285da0b0377c51aa920d842ba53e5e4d22430d5bfb38552b348ab53541e3505972578f23cd65983fca87914900bfe845b450448e1aef3031e995017",
          "sha256": "96301004908c430ba48593a699fd70538a5f0efdbf3cc02ef09b9e5e2e463145",
          "sha1": "efc02918be9971c21f72fcbbdbab750c4f1cf62e",
          "md5": "29ab14db894703ebd2454c80af6ec56f"
        }
      ]
    }
  ]
}
