{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.11.0/koruksp-0.11.0.module",
    "group": "com.futuremind.koruksp",
    "module": "koruksp",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-macosarm64-0.11.0.klib",
          "size": 12726,
          "sha512": "162062499dc3116b264b54042ba9b98dd904df4c632ee451c8d84ea17622cf563b53a104893a02558660ae473a8d977f65bc4da04c4a51dfe8182e94b97a977a",
          "sha256": "3fc28c0539582ba068421a77915d213cb1afa3bca9058b837ae28cac83faadf1",
          "sha1": "91ee26757c5aedc37a4a475c4f429b2751f80195",
          "md5": "811ff86d10ccc9003d6419ae2e9214bf"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-macosarm64-0.11.0-metadata.jar",
          "url": "koruksp-macosarm64-0.11.0-metadata.jar",
          "size": 4051,
          "sha512": "3b31f89f76157014d83c859f5eff018c540faa21ce2e2bf735b31b8d038ff36380395c62d4a477eb9fa29750ad1ba55235e5d354bc7e8046325794aa2dd90630",
          "sha256": "0a0dcb65189fc4d20dd0d0a69f3c218e9d1345d41ddc2242dda7b866dc0eda32",
          "sha1": "345fc6991536d2e130232e8681296ac1dc9b6ce7",
          "md5": "7ee3d93479ef416cf9a620190dbdd965"
        }
      ]
    }
  ]
}
