{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koruksp/0.11.0/koruksp-0.11.0.module",
    "group": "com.futuremind.koruksp",
    "module": "koruksp",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp.klib",
          "url": "koruksp-watchosarm32-0.11.0.klib",
          "size": 12745,
          "sha512": "690b730d1d8f62b462096a9492a34cd5f3c2adcafe4ba674018038e25fed764e7bb1906b24ebfc2eb74100d130eaf760dc962271987cad0d904455f4c41120ac",
          "sha256": "a49a616496c6f7e19145c0bf59a9d0f50c30daf9ff9804bdc008a33e001300c8",
          "sha1": "0094189b66107ffb9018b85da388879e47d6be0f",
          "md5": "8c56e3e3019df4d6ba2428fa150fb8a2"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "koruksp-watchosarm32-0.11.0-metadata.jar",
          "url": "koruksp-watchosarm32-0.11.0-metadata.jar",
          "size": 4051,
          "sha512": "3b31f89f76157014d83c859f5eff018c540faa21ce2e2bf735b31b8d038ff36380395c62d4a477eb9fa29750ad1ba55235e5d354bc7e8046325794aa2dd90630",
          "sha256": "0a0dcb65189fc4d20dd0d0a69f3c218e9d1345d41ddc2242dda7b866dc0eda32",
          "sha1": "345fc6991536d2e130232e8681296ac1dc9b6ce7",
          "md5": "7ee3d93479ef416cf9a620190dbdd965"
        }
      ]
    }
  ]
}
